sudo: required
services:
  - docker

before_install:
  - docker build -t azafromkaza/docker-tutorial-react -f Dockerfile.dev .

scripts:
  - docker run azafromkaza/docker-tutorial-react npm run test -- --coverage